source 'https://bitbucket.org/omegarinc/cocoapods-specs.git' # private spec repo
source 'https://github.com/CocoaPods/Specs.git' # master cocoapods spec repo

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyDemo

pod 'ORCoreData', '~> 3.1.0'
pod 'ORCommonCode-Swift', '~> 3.0.2'
pod 'ORCommonUI-Swift', '~> 3.8.2'

  pod 'Alamofire', '~> 4.3'
  pod 'AlamofireImage', '~> 3.2'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'Spartan'
  
  pod 'UIScrollView-InfiniteScroll'
  
  pod 'LGSideMenuController', '~> 2.1.1'
end
